### ISSUE TITLE
font is hard to read

### ISSUE THREAD

**Issue by phanirithvij** [jakehamilton/nixpkgs.news#1]
As a few people have mentioned on the [discourse thread](https://discourse.nixos.org/t/nixpkgs-news-a-weekly-recap-for-the-nix-community/42137/4) the font is kind of hard to read.

I suggest to use the font used by discourse/hacker news/reddit because I tend to read hours of these posts.

**Comment by jakehamilton** [comment]
Hey there! I don't have any plans to change the font from Playfair Display at the moment. Right now I think it captures the aesthetic I'm going for. A workaround currently would be to read the issues using an RSS reader.

**Comment by phanirithvij** [comment]
If the purpose of the site is for news for others to read please consider others' opinion on this topic.
