### ISSUE TITLE
Apr 21, 2024: 24.05 release correction

### ISSUE THREAD

**Issue by srid** [jakehamilton/nixpkgs.news#5]
https://nixpkgs.news/archive/2024-04-21/

> This release, NixOS 24.05 “Uakari”, is being managed by [Weijia Wang](https://github.com/wegank) and [Jonathan Ringer](https://github.com/jonringer).

However, Jonathan is not managing this release anymore [due to the ban](https://old.reddit.com/r/NixOS/comments/1ceeg8h/transparency_about_jonringers_suspension/).

**Comment by jakehamilton** [comment]
Ah, yeah, I will be mentioning this in tomorrow's issue. I'll keep this open until that's up.
